version: '3'
services:
  web:
    build: .
    container_name: todo
    ports:
      - "5000:5000"
    networks:
      - zapnet
    environment:
      FLASK_ENV: development

  zap:
    image: ghcr.io/zaproxy/zaproxy 
    container_name: zap
    ports:
      - "8080:8080"
      - "8090:8090"
    command: zap-baseline.py -t http://172.18.0.3:5000/
    networks:
      - zapnet

networks:
  zapnet:
    driver: bridge