name: Docker CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo:develop .

      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/todo:develop ./run-tests.sh
      
      - name: Run Bandit
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/todo:develop ./run-bandit.sh
      
      - name: Run dependency-check
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/todo:develop ./run-dependency-check.sh

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true       
            tags: ${{ secrets.DOCKER_USERNAME }}/todo:develop
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
