name: Docker CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo:develop .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov-report=html --html=test/test-results.html
      
      - name: Export Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /home/runner/work/Task-Manager-using-Flask/Task-Manager-using-Flask/test/test-results.html