name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo:latest .
      
      - name: Push the image to Docker Hub
        uses: docker/push-action@v3
        with:
          tags: ${{ secrets.DOCKER_USERNAME }}/todo:latest
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Run tests
        run: |
          docker run --rm todo:latest ./run-tests.sh
